
status_list = ['Posted' ,'Pending Payment', 'Accepted', 'Paid', 'Completed']

role_list = ['Client', 'Driver']

user_data = [
    {'email': 'kwame.mensah@example.com',
    'first_name': 'Kwame',
    'last_name': 'Mensah',
    'password': 'VnUVEUSY8jLD',
    'phone_number': '+233240000001',
    'role': 'Client'},
    {'email': 'akosua.boateng@example.com',
    'first_name': 'Akosua',
    'last_name': 'Boateng',
    'password': 'kTLb3k1SjnZY',
    'phone_number': '+233240000002',
    'role': 'Client'},
    {'email': 'kofi.owusu@example.com',
    'first_name': 'Kofi',
    'last_name': 'Owusu',
    'password': 'hsj1UUgEM9tZ',
    'phone_number': '+233240000003',
    'role': 'Client'},
    {'email': 'esi.ofori@example.com',
    'first_name': 'Esi',
    'last_name': 'Ofori',
    'password': 'OMEn55HU7JSj',
    'phone_number': '+233240000004',
    'role': 'Client'},
    {'email': 'yaw.asare@example.com',
    'first_name': 'Yaw',
    'last_name': 'Asare',
    'password': 'isHCfedeTssr',
    'phone_number': '+233240000005',
    'role': 'Client'},
    {'email': 'abena.nyarko@example.com',
    'first_name': 'Abena',
    'last_name': 'Nyarko',
    'password': 'gnixUMG9izMn',
    'phone_number': '+233240000006',
    'role': 'Client'},
    {'email': 'kojo.agyeman@example.com',
    'first_name': 'Kojo',
    'last_name': 'Agyeman',
    'password': 'qegGi5393yUB',
    'phone_number': '+233240000007',
    'role': 'Driver'},
    {'email': 'afia.doku@example.com',
    'first_name': 'Afia',
    'last_name': 'Doku',
    'password': 'L0dFb50DRMpC',
    'phone_number': '+233240000008',
    'role': 'Driver'},
    {'email': 'kweku.baah@example.com',
    'first_name': 'Kweku',
    'last_name': 'Baah',
    'password': 'DRXqUjvA8z5Z',
    'phone_number': '+233240000009',
    'role': 'Driver'},
    {'email': 'ama.quansah@example.com',
    'first_name': 'Ama',
    'last_name': 'Quansah',
    'password': 'HqVH86uYzq3m',
    'phone_number': '+233240000010',
    'role': 'Driver'}
]


